export const FETCH_ALBUMS_START = "FETCH_ALBUMS_START";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAIL = "FETCH_ALBUMS_FAIL";

export const FETCH_ARTIST_START = "FETCH_ARTIST_START";
export const FETCH_ARTIST_SUCCESS = "FETCH_ARTIST_SUCCESS";
export const FETCH_ARTIST_FAIL = "FETCH_ARTIST_FAIL";

export const FETCH_TRACK_START = "FETCH_TRACK_START";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";
export const FETCH_TRACK_FAIL = "FETCH_TRACK_FAIL";

export const FETCH_ALBUM_DETAIL_START = "FETCH_ALBUM_DETAIL_START";
export const FETCH_ALBUM_DETAIL_SUCCESS = "FETCH_ALBUM_DETAIL_SUCCESS";
export const FETCH_ALBUM_DETAIL_FAIL = "FETCH_ALBUM_DETAIL_FAIL";